{% set version = '0.1.3' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-packer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/packer_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/packer/packer_{{ version }}.tar.gz
  sha256: b09d36d35c2eff8655bc2257988f204687de4492e97cb31c5a5dd6469eb2a12c

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-assertthat
    - r-cli
    - r-fs
    - r-htmlwidgets
    - r-jsonlite
    - r-roxygen2
    - r-rprojroot
    - r-rstudioapi
    - r-usethis
  run:
    - r-base
    - r-assertthat
    - r-cli
    - r-fs
    - r-htmlwidgets
    - r-jsonlite
    - r-roxygen2
    - r-rprojroot
    - r-rstudioapi
    - r-usethis

test:
  commands:
    - $R -e "library('packer')"           # [not win]
    - "\"%R%\" -e \"library('packer')\""  # [win]

about:
  home: https://packer.john-coene.com
  dev_url: https://github.com/JohnCoene/packer
  license: MIT
  summary: Enforces good practice and provides convenience functions to make work with 'JavaScript'
    not just easier but also scalable. It is a robust wrapper to 'NPM', 'yarn', and
    'webpack' that enables to compartmentalize 'JavaScript' code, leverage 'NPM' and
    'yarn' packages, include 'TypeScript', 'React', or 'Vue' in web applications, and
    much more.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: packer
# Title: An Opinionated Framework for Using 'JavaScript'
# Date: 2022-05-28
# Version: 0.1.3
# Authors@R: person(given = "John", family = "Coene", role = c("aut", "cre"), email = "jcoenep@gmail.com", comment = c(ORCID = "0000-0002-6637-4107"))
# Description: Enforces good practice and provides convenience functions to make work with 'JavaScript' not just easier but also scalable. It is a robust wrapper to 'NPM', 'yarn', and 'webpack' that enables to compartmentalize 'JavaScript' code, leverage 'NPM' and 'yarn' packages, include 'TypeScript', 'React', or 'Vue' in web applications, and much more.
# License: MIT + file LICENSE
# Encoding: UTF-8
# RoxygenNote: 7.2.0
# Imports: fs, cli, usethis, jsonlite, roxygen2, rprojroot, rstudioapi, assertthat, htmlwidgets
# URL: https://github.com/JohnCoene/packer, https://packer.john-coene.com
# BugReports: https://github.com/JohnCoene/packer/issues
# Suggests: testthat, covr, golem
# NeedsCompilation: no
# Packaged: 2022-05-28 09:13:23 UTC; john
# Author: John Coene [aut, cre] (<https://orcid.org/0000-0002-6637-4107>)
# Maintainer: John Coene <jcoenep@gmail.com>
# Repository: CRAN
# Date/Publication: 2022-05-28 09:30:02 UTC
